name: Prism
options:
  bundleIdPrefix: com.prism
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "16.2"
  generateEmptyDirectories: true
  groupSortPosition: top

configFiles:
  Debug: Config/Debug.xcconfig
  Release: Config/Release.xcconfig

settings:
  base:
    SWIFT_VERSION: "6.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios-spm
    from: "5.0.0"

targets:
  Prism:
    type: application
    platform: iOS
    sources:
      - path: Prism
        excludes:
          - "**/.DS_Store"
    resources:
      - path: Prism/Resources
        buildPhase: resources
    info:
      path: Prism/Info.plist
      properties:
        SupabaseURL: $(SUPABASE_URL)
        SupabaseAnonKey: $(SUPABASE_ANON_KEY)
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.prism.app
        INFOPLIST_KEY_CFBundleDisplayName: Prism
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        GENERATE_INFOPLIST_FILE: YES
        ENABLE_PREVIEWS: YES
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: Prism/Prism.entitlements
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
    dependencies:
      - package: Supabase
        product: Supabase
      - package: RevenueCat
        product: RevenueCat
      - package: RevenueCat
        product: RevenueCatUI

schemes:
  Prism:
    build:
      targets:
        Prism: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
